position:
  pos1:
    latitude_deg: 38.1617390
    longitude_deg: -122.4536428
    relative_altitude_m: 10.0
    speed_m_s: 5.0
    is_fly_through: false
    gimbal_pitch_deg: 0.0
    gimbal_yaw_deg: 0.0
  pos2:
    latitude_deg: 38.1620414
    longitude_deg: -122.4543325
    relative_altitude_m: 10.0
    speed_m_s: 2.0
    is_fly_through: true
    gimbal_pitch_deg: 0.0  
    gimbal_yaw_deg: 0.0 
  pos3:
    latitude_deg: 38.1620414
    longitude_deg: -122.4549426
    relative_altitude_m: 10.0
    speed_m_s: 5.0
    is_fly_through: true
    gimbal_pitch_deg: 0.0
    gimbal_yaw_deg: 0.0 
  pos4:
    latitude_deg: 38.1617807
    longitude_deg: -122.4551681
    relative_altitude_m: 10.0
    speed_m_s: 2.0 
    is_fly_through: false
    gimbal_pitch_deg: 0.0 
    gimbal_yaw_deg: 0.0 
  pos5:
    latitude_deg: 38.1617586
    longitude_deg: -122.4546649 
    relative_altitude_m: 10.0
    speed_m_s: 5.0 
    is_fly_through: false
    gimbal_pitch_deg: 0.0
    gimbal_yaw_deg: 0.0 
  pos6:
    latitude_deg: 38.1615290
    longitude_deg: -122.4546111
    relative_altitude_m: 10.0
    speed_m_s: 5.0 
    is_fly_through: false
    gimbal_pitch_deg: 0.0
    gimbal_yaw_deg: 0.0 

